spring.application.name=email-service

spring.main.allow-bean-definition-overriding=true
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

kafka.topic.email=email-queue
spring.kafka.bootstrap-servers=20.207.207.6:9092
email.retry.interval=60000

#eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/
#eureka.instance.hostname=localhost
#eureka.instance.prefer-ip-address=true

#spring.rabbitmq.host=localhost
#spring.rabbitmq.port=5672
#spring.rabbitmq.username=guest
#spring.rabbitmq.password=guest
#spring.rabbitmq.listener.simple.acknowledge-mode=manual

#spring.rabbitmq.host=rabbitmq
#spring.rabbitmq.port=5672
#spring.rabbitmq.username=admin
#spring.rabbitmq.password=admin
#spring.rabbitmq.listener.simple.acknowledge-mode=manual
#rabbitmq.email.max-retries=3
#rabbitmq.exchange.name=email.exchange
#rabbitmq.queue.name=email.queue
#rabbitmq.routing.key=email.tracking

server.port=8083