syntax = "proto3";

package userservice;

option java_multiple_files = true;
option java_package = "com.mailforge.userservice.grpc";
option java_outer_classname = "UserServiceProto";

service UserService {

    rpc GetUser(GetUserRequest) returns (GetUserResponse);

    rpc UpdateUserPlan(UpdateUserPlanRequest) returns (UpdateUserPlanResponse);
}

message GetUserRequest {
    string userId = 1;
}

message GetUserResponse {
    string userId = 1;
    string email = 2;
    string planType = 3;
    string status = 4;
}

message UpdateUserPlanRequest {
    string userId = 1;
    string planType = 2; // FREE, DEV, UNLIMITED
}

message UpdateUserPlanResponse {
    string status = 1; // SUCCESS, FAILED
}
