spring.application.name=email-consumer-service

server.port=8085

spring.data.mongodb.uri=mongodb://admin_user:password@localhost:8000/emailconsumerdb?authSource=admin

spring.kafka.bootstrap-servers=20.207.207.6:9092
spring.kafka.consumer.group-id=email-consumer-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.enable-auto-commit=false
kafka.email.max-retries=3

mail.sender.email=mailforge28@gmail.com
mail.sender.name=MailForge



