spring.application.name=quota-service

server.port=8088

SPRING_DATASOURCE_DRIVER-CLASS-NAME=org.postgresql.Driver;
SPRING_DATASOURCE_PASSWORD=password;
SPRING_DATASOURCE_URL=jdbc:postgresql://quota-service-db:5432/quotadb;
SPRING_DATASOURCE_USERNAME=admin_user;
SPRING_JPA_HIBERNATE_DDL_AUTO=update;
SPRING_SQL_INIT_MODE=always

grpc.server.port=9092
