spring.application.name=project-service

#CREATED DOCKER DB, FOR USING MONGO ATLAS UNCOMMENT AND USE
#spring.data.mongodb.uri=mongodb+srv://sujitkumarshaw029_db_user:nctaxPP0MhxI0oTa@mailforge-project-servi.g27vnb2.mongodb.net/MailForge?retryWrites=true&w=majority
#spring.data.mongodb.database=MailForge
#spring.config.import=optional:configserver:http://host.docker.internal:8888

server.port=8082

spring.main.allow-bean-definition-overriding=true
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

#eureka.client.serviceUrl.defaultZone=http://host.docker.internal:8761/eureka/